import { useState } from 'react'
import { useSessionStore } from '../../store/sessionStore'
import { useToastStore } from '../../store/toastStore'

interface Props {
  open: boolean
  onClose: () => void
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
}

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return m > 0 ? `${m}m ${s}s` : `${s}s`
}

export function TracklistPDFDialog({ open, onClose }: Props): JSX.Element | null {
  const [artist, setArtist] = useState('')
  const [album, setAlbum] = useState('')
  const [notes, setNotes] = useState('')
  const [busy, setBusy] = useState(false)

  const clips = useSessionStore((s) => s.clips)
  const tracks = useSessionStore((s) => s.tracks)
  const currentFilePath = useSessionStore((s) => s.currentFilePath)
  const toast = useToastStore((s) => s.add)

  if (!open) return null

  const projectName = currentFilePath
    ? currentFilePath.split(/[\\/]/).pop()?.replace(/\.limina$/, '') ?? 'Untitled Session'
    : 'Untitled Session'

  const trackMap = new Map(tracks.map((t) => [t.id, t]))

  // Build sorted cue list from all clips
  const cues = [...clips]
    .sort((a, b) => a.startTime - b.startTime)
    .map((clip, i) => {
      const track = trackMap.get(clip.trackId)
      const effectiveDuration = clip.duration - clip.trimStart - clip.trimEnd
      return {
        num: i + 1,
        name: clip.fileName.replace(/\.[^.]+$/, ''),
        trackName: track?.name ?? '',
        startTime: clip.startTime,
        duration: effectiveDuration,
      }
    })

  const totalDuration = cues.reduce((sum, c) => Math.max(sum, c.startTime + c.duration), 0)

  const generateHTML = (): string => {
    const rows = cues.map((c) => `
      <tr>
        <td class="num">${c.num}</td>
        <td class="name">${c.name}</td>
        <td class="lane">${c.trackName}</td>
        <td class="time">${formatTime(c.startTime)}</td>
        <td class="dur">${formatDuration(c.duration)}</td>
      </tr>`).join('')

    const metaLine = [artist, album].filter(Boolean).join(' — ')
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

    return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #111; padding: 48px 56px; font-size: 13px; }
  h1 { font-size: 26px; font-weight: 700; letter-spacing: -0.02em; margin-bottom: 4px; }
  .meta { color: #555; font-size: 14px; margin-bottom: 4px; }
  .session-date { color: #999; font-size: 12px; margin-bottom: 32px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 32px; }
  thead th { text-align: left; border-bottom: 2px solid #222; padding: 6px 10px 8px; font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; color: #444; }
  tbody td { padding: 9px 10px; border-bottom: 1px solid #e8e8e8; vertical-align: top; }
  tbody tr:last-child td { border-bottom: none; }
  .num { color: #aaa; width: 32px; }
  .name { font-weight: 500; }
  .lane { color: #666; font-size: 12px; }
  .time { font-family: 'Courier New', monospace; color: #333; width: 56px; }
  .dur { font-family: 'Courier New', monospace; color: #888; width: 64px; }
  .totals { font-size: 12px; color: #666; border-top: 1px solid #ccc; padding-top: 16px; margin-bottom: 24px; }
  .notes { font-size: 12px; color: #444; line-height: 1.6; border-left: 3px solid #ddd; padding-left: 12px; margin-bottom: 32px; }
  .footer { font-size: 10px; color: #bbb; border-top: 1px solid #e8e8e8; padding-top: 12px; }
</style>
</head>
<body>
  <h1>${projectName}</h1>
  ${metaLine ? `<div class="meta">${metaLine}</div>` : ''}
  <div class="session-date">${date}</div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Track</th>
        <th>Start</th>
        <th>Duration</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="totals">${cues.length} track${cues.length !== 1 ? 's' : ''} · Total duration: ${formatDuration(totalDuration)}</div>

  ${notes ? `<div class="notes">${notes.replace(/\n/g, '<br>')}</div>` : ''}

  <div class="footer">Generated by Limina Studio</div>
</body>
</html>`
  }

  const handleExport = async (): Promise<void> => {
    setBusy(true)
    try {
      const html = generateHTML()
      const result = await window.electronAPI.exportTracklistPDF(html)
      if (result) {
        toast('Track listing saved', 'success')
        onClose()
      }
    } catch (e) {
      toast(`PDF export failed: ${e}`, 'error')
    } finally {
      setBusy(false)
    }
  }

  return (
    <div
      className="fixed inset-0 bg-black/70 flex items-center justify-center z-50"
      onClick={(e) => { if (e.target === e.currentTarget && !busy) onClose() }}
    >
      <div className="bg-surface-panel border border-surface-border rounded-xl p-6 w-[420px] shadow-2xl flex flex-col gap-4">
        <div className="flex items-center justify-between">
          <h2 className="text-base font-semibold text-gray-200">Export Track Listing</h2>
          <button onClick={onClose} disabled={busy} className="text-gray-600 hover:text-gray-300 disabled:opacity-30">✕</button>
        </div>

        <p className="text-xs text-gray-500">{cues.length} tracks · {projectName}</p>

        <div className="flex flex-col gap-3">
          <Field label="Artist">
            <input
              type="text"
              placeholder="e.g. Stan Grof"
              value={artist}
              onChange={(e) => setArtist(e.target.value)}
              className="flex-1 bg-surface-hover border border-surface-border rounded px-2 py-1.5 text-xs text-gray-200 placeholder-gray-600 outline-none focus:border-accent/60"
            />
          </Field>
          <Field label="Album / Set">
            <input
              type="text"
              placeholder="e.g. Spring Intensive 2025"
              value={album}
              onChange={(e) => setAlbum(e.target.value)}
              className="flex-1 bg-surface-hover border border-surface-border rounded px-2 py-1.5 text-xs text-gray-200 placeholder-gray-600 outline-none focus:border-accent/60"
            />
          </Field>
          <Field label="Notes">
            <textarea
              placeholder="Optional notes for the PDF…"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              rows={3}
              className="flex-1 bg-surface-hover border border-surface-border rounded px-2 py-1.5 text-xs text-gray-200 placeholder-gray-600 outline-none focus:border-accent/60 resize-none"
            />
          </Field>
        </div>

        {/* Preview of cue list */}
        <div className="bg-surface-base rounded border border-surface-border max-h-44 overflow-y-auto">
          <table className="w-full text-[10px]">
            <thead>
              <tr className="border-b border-surface-border">
                <th className="text-left px-2 py-1.5 text-gray-600 font-medium w-6">#</th>
                <th className="text-left px-2 py-1.5 text-gray-600 font-medium">Title</th>
                <th className="text-left px-2 py-1.5 text-gray-600 font-medium w-14">Start</th>
                <th className="text-left px-2 py-1.5 text-gray-600 font-medium w-14">Dur</th>
              </tr>
            </thead>
            <tbody>
              {cues.map((c) => (
                <tr key={c.num} className="border-b border-surface-border/50 last:border-0">
                  <td className="px-2 py-1 text-gray-600">{c.num}</td>
                  <td className="px-2 py-1 text-gray-300 truncate max-w-0 w-full">{c.name}</td>
                  <td className="px-2 py-1 font-mono text-gray-500">{formatTime(c.startTime)}</td>
                  <td className="px-2 py-1 font-mono text-gray-600">{formatDuration(c.duration)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <button
          onClick={handleExport}
          disabled={busy}
          className="w-full py-2 bg-accent hover:bg-accent-hover disabled:opacity-40 text-white text-sm font-medium rounded-lg transition-colors"
        >
          {busy ? 'Generating PDF…' : 'Save PDF…'}
        </button>
      </div>
    </div>
  )
}

function Field({ label, children }: { label: string; children: React.ReactNode }): JSX.Element {
  return (
    <div className="flex items-start gap-3">
      <span className="text-xs text-gray-500 w-16 shrink-0 pt-1.5">{label}</span>
      <div className="flex-1">{children}</div>
    </div>
  )
}
